### ISSUE TITLE
Bug po odpaleniu gry

### ISSUE THREAD

**Issue by Zigigigi** [Mrucznik/Mrucznik-RP-2.5#344]
Witaj mrucznik :D dzięki za wstawkę mapy. Chciałem ją odpalić żeby przetestować z kolegami, ponieważ od jakoś 6 miesięcy uczę się pawn :D Niestety po odpaleniu mapy na vps napotkałem dość poważny problem, którego nie jestem w stanie rozwiązać sam. Nie widać innych postaci, gdy stoimy blisko siebie, widać jedynie chaty lokalne. Kolejnym problemem jest brak widoczności samochodów. Mapę odpaliłem z dockerem, wiec chyba wszystko powinno działać. Mógłbyś powiedzieć jak to rozwiązać?

**Comment by Mrucznik** [comment]
Hej @Zigigigi naprawiłeś ten problem?
Jeśli tak, daj znać w jaki sposób, aby w razie czego inni mogli wiedzieć, jak to zrobić ;)
