### ISSUE TITLE
Błąd kompilacji

### ISSUE THREAD

**Issue by viper2013** [Mrucznik/Mrucznik-RP-2.5#345]
Cześć Mrucznik!
przypadkowo trafiłem dziś na Twojego gita i z wielką chęcią chciałem odpalić serwer aby poczuć się jak za starych dobrych czasów. Pobrałem wszystkie pliki według instrukcji i serwer odpalił się poprawnie z dockerem, jednak jak ktoś wcześniej pisał wystąpił problem braku widoczności pojazdów. Pomyślałem, więc że spróbuję skompilować skrypt, zainstalowałem sampctl i gdy wpisałem polecenie _**sampctl package ensure**_ uzyskałem taki efekt:

![image](https://user-images.githubusercontent.com/32649577/117344725-01076c80-aea6-11eb-8121-ca697f129f4c.png)

Problem jednak pojawia się po wydaniu drugiego polecenia kompilacji _**sampctl package build**_ (kod błędu: 3221226519)
![image](https://user-images.githubusercontent.com/32649577/117344843-2b592a00-aea6-11eb-89d7-73c55e8bc650.png)

Będę bardzo wdzięczny za pomoc i ewentualne wskazówki, ponieważ darzę ten projekt wielkim sentymentem.

**Comment by viper2013** [comment]
@Mrucznik Masz może jakiś pomysł dlaczego po uruchomieniu skryptu za pomocą polecenia docker-compose up, pojazdy są niewidoczne?

**Comment by Mrucznik** [comment]
Cześć, problem wygląda jak crash kompilatora, mógłbyś podać więcej informacji np. na jakim systemie kompiluejsz?
Wszystkie pojazdy są niewidoczne? Może to błąd z virtual worldem innym niż 0.
Możliwe, że baza danych nie jest poprawna, bo tego nie sprawdzałem jak wrzucałem kod. Sprawdź, czy nie ma jakichś błędów error logach mysql.

**Comment by gumbalowsky** [comment]
"sampctl package ensure" nie pobiera niektórych paczek, trzeba się samemu do nich dokopać, pobrać je i wrzucić w lokalizację z wszystkimi paczkami od sampctl.
Miałem dokładnie ten sam problem za każdym razem jak tworzyłem środowisko, niektórym przez niewiadomą rzecz nie pobiera tych plików.

Te pliki trzeba pobrać i wrzucić:

> https://github.com/emmet-jones/New-SA-MP-callbacks
> https://github.com/Wuzi/vending

**Comment by ajax-git** [comment]
> Cześć, problem wygląda jak crash kompilatora, mógłbyś podać więcej informacji np. na jakim systemie kompiluejsz?
> Wszystkie pojazdy są niewidoczne? Może to błąd z virtual worldem innym niż 0.
> Możliwe, że baza danych nie jest poprawna, bo tego nie sprawdzałem jak wrzucałem kod. Sprawdź, czy nie ma jakichś błędów error logach mysql.

Baza jest nie kompletna tak btw, sporo tabel brakuje. Po logach mozna dojsc co czego brakuje.

**Comment by ajax-git** [comment]
> @Mrucznik Masz może jakiś pomysł dlaczego po uruchomieniu skryptu za pomocą polecenia docker-compose up, pojazdy są niewidoczne?

Mam sampa postawionego na zwyklym vpsie i jest dokladnie to samo. Testowalem na roznych branchach, niezaleznie od tego czy to v2.7.9 czy to najnowsza wersja - efekt jest takim sam. Oczywiscie zadnych bledow od mysqla zwiazanych z pojazdami.

@Mrucznik

**Comment by Mrucznik** [comment]
> Baza jest nie kompletna tak btw, sporo tabel brakuje. Po logach mozna dojsc co czego brakuje.

Tak myślałem, wrzucę poprawioną wersję.

Odnośnie tych pojazdów, spróbuj wywołać komendę /setvw 0

**Comment by ajax-git** [comment]
> > Baza jest nie kompletna tak btw, sporo tabel brakuje. Po logach mozna dojsc co czego brakuje.
> 
> Tak myślałem, wrzucę poprawioną wersję.
> 
> Odnośnie tych pojazdów, spróbuj wywołać komendę /setvw 0 0

Bylem na virtual worldzie 0, pojazdow nie widac, a sa normalnie zespawnowane (mozna sie do nich nawet tepac). Moze to ten fajny nex-ac cos knoci?

**Comment by Mrucznik** [comment]
Jeśli są zanaczone na mapie i można do nich wsiadać, ale ich nie widać, to znaczy, że są na innym interiorze.

**Comment by Mrucznik** [comment]
Nowa baza danych wrzucona #c465bec7fd9dec5593fda3bccc7eb824822865b6

**Comment by Mrucznik** [comment]
Hmm, faktycznie nie ma pojazdów. Nie wiem z czego to wynika.

**Comment by Mrucznik** [comment]
Zamykam i przenoszę dyskusję nad problemem do https://github.com/Mrucznik/Mrucznik-RP-2.5/issues/346
