### ISSUE TITLE
Brak pojazdów

### ISSUE THREAD

**Issue by Mrucznik** [Mrucznik/Mrucznik-RP-2.5#346]
Po uruchomieniu serwera nie widać pojazdów, nie da się do nich wsiąść (ani enterem ani /entercar).
Da się do nich teleportować, nie widać błędów w logach.

**Comment by ajax-git** [comment]
Moze kto kwestia bibliotek?

**Comment by daffyyyy** [comment]
I jak tam idzie? :D

**Comment by Mrucznik** [comment]
niestety, brak postępów w tej kwestii
ogólnie to ten gamemode jest oparty na prehistorycznych pluginach do mysql, których możliwe, że już w ogóle nie ma skąd pobrać i nie działają na nowszych systemach (my chyba byliśmy wtedy na ubuntu 12 lub 14)
moja próba przeniesienia tego na nowsze pluginy jest tutaj: https://github.com/Mrucznik/Mrucznik-RP-2.5/tree/new_mysql
ale nie dokończyłem tego

jak ktoś by chciał postawić serwer, to musi się liczyć z tym, że fakt konieczności użycia tak starych pluginów może być problematyczny

możlwie, że serwer nie wstaje, bo nie ma skąd pobrać modeli, w tym przypadku, należy odpalić resouces_server.go (pobrać golanga i `go run resources_server.go`)
repo z modelami: https://github.com/Mrucznik/Mrucznik-RP-models

nie pamiętam, czy to sprawdzałem, ale to może być jakiś trop

**Comment by xselectx** [comment]
Brak modeli, można obejść zmieniając wartość w useartwork z 1 na 0 w server.cfg

**Comment by Mrucznik** [comment]
Trzeba było stworzyć link ln -s . scriptfiles/DANGEROUS_SERVER_ROOT
