### ISSUE TITLE
Bug z AJ

### ISSUE THREAD

**Issue by gumbalowsky** [Mrucznik/Mrucznik-RP-2.5#364]
Uzywajac cleo na desync(albo teleportujacy do przodu na centymetry co kilka ms) mozna wyjsc z AJ, interior/vw zmienia sie przez intek na gorze DMV.

**Comment by Mrucznik** [comment]
można banować gdy ktoś wchodzi do interioru a ma vw aj

**Comment by gumbalowsky** [comment]
https://github.com/Mrucznik/Mrucznik-RP-2.5/pull/368
