### ISSUE TITLE
Powrót do poprzedniej pozycji - zły VW

### ISSUE THREAD

**Issue by Allerek** [Mrucznik/Mrucznik-RP-2.5#387]
Powrót do poprzedniej pozycji znajdującej się na vw0 powoduje ustawienie VW innego niż '0' - wymaga poproszenia administratora o ustawienie vw 0

**Comment by Hubii03** [comment]
Bo serwer przy wchodzeniu na serwer nie ustawia domyślnie VW - Jest już request który to wymusza

**Comment by Pawlash** [comment]
issue #399  to samo

potwierdzam, to się dzieje - w szczególności, gdy zrobilo się szybkiego reloga, i szybko nacisneło się przycisk "Tak"

4 lata temu na bank tak nie było, ale co ciekawe w dzień końca serwera był to już powszechny problem, i adminom się non stop pisalo, zeby przestawili vw na 0(bo czesto crashowalo, to trzeba bylo robic relogi) - gdy wbiłem w polowie stycznia przed czystką, sam miałem ustawiony nieprawidłowy vw jeszcze sprzed eventu ostatniego

**Comment by Mrucznik** [comment]
duplikat #399

**Comment by Mrucznik** [comment]
https://samp.mrucznik-rp.pl
