### ISSUE TITLE
Przy przywracaniu pozycji po logowaniu wyrzuca do innego virtualworlda i nikogo nie widać po zrespieniu się

### ISSUE THREAD

**Issue by Mrucznik** [Mrucznik/Mrucznik-RP-2.5#389]

**Comment by Pawlash** [comment]
issue #399 - to samo

potwierdzam, to się dzieje - w szczególności, gdy zrobilo się szybkiego reloga, i szybko nacisneło się przycisk "Tak"

4 lata temu na bank tak nie było, ale co ciekawe w dzień końca serwera był to już powszechny problem, i adminom się non stop pisalo, zeby przestawili vw na 0(bo czesto crashowalo, to trzeba bylo robic relogi) - gdy wbiłem w polowie stycznia przed czystką, sam miałem ustawiony nieprawidłowy vw jeszcze sprzed eventu ostatniego
